package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSalesman;
import org.linlinjava.litemall.db.domain.LitemallSalesmanExample;

public interface LitemallSalesmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    long countByExample(LitemallSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    int insert(LitemallSalesman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSalesman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    LitemallSalesman selectOneByExample(LitemallSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    LitemallSalesman selectOneByExampleSelective(@Param("example") LitemallSalesmanExample example, @Param("selective") LitemallSalesman.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    List<LitemallSalesman> selectByExampleSelective(@Param("example") LitemallSalesmanExample example, @Param("selective") LitemallSalesman.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    List<LitemallSalesman> selectByExample(LitemallSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    LitemallSalesman selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSalesman.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    LitemallSalesman selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    LitemallSalesman selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSalesman record, @Param("example") LitemallSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSalesman record, @Param("example") LitemallSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSalesman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSalesman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallSalesmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_salesman
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}